export const INTERESTED: string = "Interessado";
export const CPF: string = "CPF";
export const SELECTED_SERVICE:string = "Serviço escolhido"
export const SERVICE_LOCATION: string = "Local de atendimento";
export const SCHEDULING_DATE: string = "Agendamento para";
export const TICKET_WINDOW: string = "Guichê";
export const NECESSARY_DOCUMENTS: string = "Documentos necessários";
export const NECESSARY_FIRST_ITEM: string = "DOCUMENTOS NECESSÁRIOS E MAIS INFORMAÇÕES, ACESSE A CARTA DE SERVIÇOS ";
export const OPERATING_ALVARA: string = "Alvará de funcionamento";
export const NECESSARY_SECOND_ITEM: string = "SE O DIA DE SEU AGENDAMENTO FOR DECLARADO PONTO FACULTATIVO SERÁ NECESSÁRIO REALIZAR O REAGENDAMENTO DO SEU ATENDIMENTO.";
export const SHARE: string = "Compartilhar";
export const PRINT: string = "Imprimir";
export const CLOSE_BTN: string = "Fechar";
export const REQUESTED_SCHEDULING: string = "Agendamento solicitado em";
export const SERVICE_STEP_ONE: string = "Serviço"
export const LOCATION_DATE_STEP_TWO: string = "Data e local"
export const CONFIRMATION_STEP_TRHEE: string = "Confirmação"

export const OPERATING_ALVARA_URL: string = "https://manausatende.manaus.am.gov.br/empresa/alvara/"